[env:adafruit_feather_esp32_v2]
platform = espressif32
board = adafruit_feather_esp32_v2
framework = arduino
monitor_speed = 115200
upload_speed = 921600
lib_deps =
    adafruit/Adafruit BME280 Library
    adafruit/Adafruit SGP30 Sensor
    https://github.com/DFRobot/DFRobot_HumanDetection.git
    knolleary/PubSubClient
    bblanchon/ArduinoJson
build_flags =
    -DCORE_DEBUG_LEVEL=1
